name: mayberks_me
description: My flutter portfolio website
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  morphing_text: ^1.0.1
  mysql_manager: ^1.1.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Epilogue
      fonts:
        - asset: assets/fonts/Epilogue-Thin.ttf
          weight: 100
        - asset: assets/fonts/Epilogue-SemiBold.ttf
          weight: 200
        - asset: assets/fonts/Epilogue-Regular.ttf
          weight: 300
        - asset: assets/fonts/Epilogue-Medium.ttf
          weight: 400
        - asset: assets/fonts/Epilogue-Light.ttf
          weight: 500
        - asset: assets/fonts/Epilogue-Italic.ttf
          weight: 600
        - asset: assets/fonts/Epilogue-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Epilogue-Black.ttf
          weight: 800
        - asset: assets/fonts/Epilogue-Bold.ttf
          weight: 900
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 100
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 200
        - asset: assets/fonts/Sora-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Sora-Light.ttf
          weight: 400
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 600
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Sora-Thin.ttf
          weight: 800