name: mayberks_me
description: My flutter portfolio website
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.2
  font_awesome_flutter: ^10.4.0
  morphing_text: ^1.0.1
  web_smooth_scroll: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
